services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
